sudo: true
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
    - nvm install 0.12
    - nvm use 0.12
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - npm install -g dat
    - conda create --yes --quiet -n test pandas pip pyyaml setuptools
    - source activate test
    - python setup.py install
script:
    - python setup.py test
