sudo: true
language: python
python:
    - "2.7"
before_install:
    - nvm install 0.12
    - nvm use 0.12
install:
    - npm install -g dat
    - python setup.py install
script:
    - python tests/test.py
